import assert from 'node:assert/strict';
import { createResidentEchoRuntime } from '../../src/components/pond-gl-test3/echo-resident/runtime';
import { input, layout } from './fixture';

const runtime = createResidentEchoRuntime({ seed: 9, layout });
runtime.step({ ...input, reducedMotion: true }, 0);
assert.equal(typeof runtime.moveDrag, 'function', '驻留运行时必须接收拖拽位置');
const start = runtime.getSnapshot().pose;
runtime.setInteraction({ pointerDown: true });
runtime.moveDrag({ x: start.sx + 80, y: start.sy + 25 });
const moved = runtime.getSnapshot().pose;
assert.equal(moved.sx, start.sx + 80, 'GL与命中层必须立即读取同一拖拽坐标');
assert.equal(moved.sy, start.sy + 25);
runtime.step({ ...input, reducedMotion: false }, 200);
assert.equal(runtime.getSnapshot().pose.sx, moved.sx, '按下拖动时主动漂移不得抢位置');
runtime.moveDrag({ x: -1000, y: -1000 });
const edge = runtime.getSnapshot().pose;
assert.ok(edge.sx - edge.haloRadiusPx >= 16, '拖动不能把圆圈移出屏幕');
assert.ok(edge.sy - edge.haloRadiusPx >= 92, '拖动不能覆盖头部控件');
runtime.endDrag();
runtime.setInteraction({ pointerDown: false });
const released = runtime.step(input, 250).pose;
assert.ok(Math.hypot(released.sx - edge.sx, released.sy - edge.sy) < 0.3, '放开应从落点平滑恢复漂移');
runtime.step({ ...input, playback: 'playing' }, 300);
const playing = runtime.getSnapshot().pose;
runtime.setInteraction({ pointerDown: true });
runtime.moveDrag({ x: 600, y: 600 });
assert.equal(runtime.getSnapshot().pose.sx, playing.sx, '播放锁不能被拖拽位置覆盖');
runtime.destroy();
console.log('拖拽：同帧位置、控件边界、按下冻结、释放连续与播放互斥通过');
